---
- name: Install packages for pyenv.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zlib-devel
    - bzip2
    - bzip2-devel
    - readline-devel
    - sqlite
    - sqlite-devel
    - openssl-devel
